jobs:
  - job: build_conan_wine_image
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 20
    steps:
    - task: Docker@2
      displayName: 'Login to Container registry'
      inputs:
        command: login
        containerRegistry: githubContainerRegistry
    - task: Docker@2
      displayName: 'Build and push'
      inputs:
        Dockerfile: docker/wine/Dockerfile
        buildContext: docker/wine/
        command: buildAndPush
        tags: |
          ghcr.io/Tereius/ConanWine:latest
