jobs:
  - job: build_conan_wine_image
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 20
    steps:
    - task: Docker@2
      displayName: 'Login to Container registry'
      inputs:
        command: login
        containerRegistry: githubContainerRegistry
    - task: Docker@2
      displayName: 'Build and push'
      inputs:
        repository: ghcr.io/tereius/conan-wine
        Dockerfile: docker/wine/Dockerfile
        buildContext: docker/wine/
        command: buildAndPush
        tags: |
          $(Build.SourceBranchName)
          latest
    - task: Docker@2
      displayName: 'Logout'
      inputs:
        command: logout
        containerRegistry: githubContainerRegistry

  - job: build_conan_ubuntu_image
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 20
    steps:
    - task: Docker@2
      displayName: 'Login to Container registry'
      inputs:
        command: login
        containerRegistry: githubContainerRegistry
    - task: Docker@2
      displayName: 'Build and push'
      inputs:
        repository: ghcr.io/tereius/conan-ubuntu
        Dockerfile: docker/ubuntu/Dockerfile
        buildContext: docker/ubuntu/
        command: buildAndPush
        tags: |
          $(Build.SourceBranchName)
          latest
    - task: Docker@2
      displayName: 'Logout'
      inputs:
        command: logout
        containerRegistry: githubContainerRegistry
